production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  vapid_public_key: <%= ENV['VAPID_PUBLIC_KEY'] %>
  vapid_private_key: <%= ENV['VAPID_PRIVATE_KEY'] %>

development:
  vapid_public_key: "BBIA4ROwv6LMAg9Mkqesa6ib2ESAHli31HOp4ANZiMEvnoSVWBJAQP0HfBG_liglI5bICmkDs360foCE0kD7jsE="
  vapid_private_key: "UDDTExjXoyex5d0MiNYZY4JpdyBDxKTFatDh2N9JYiU="
