production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  secret_key_base: <%= Rails.application.credentials.fetch(:secret_key_base) %>

test:
  secret_key_base: <%= Rails.application.credentials.fetch(:secret_key_base) %>
